<?php

namespace AppBundle\Repository;

/**
 * locationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class locationRepository extends \Doctrine\ORM\EntityRepository
{
}
