<?php

namespace AppBundle\Repository;

/**
 * pokemonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pokemonRepository extends \Doctrine\ORM\EntityRepository
{
}
